### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by scrowner** [funkymonkeymonk/library-access#2] opened 2019-07-28 22:23 UTC
Is there a deck # limit?
Chrome: Version 75.0.3770.142
iMac with Sierra 10.12.6
Sync tool V0.3

Finds all decks in my Vault account: 289 COTA and AOA
Moving to DecksofKeyforge there are no decks listed and pressing SYNC creates and error screen of: No decks accessed from Master Vault. Click "Access Master Vault" first. Tried using same window in chrome and different tabs in chrome. No Luck.

**Comment by david-torres** [comment] 2019-07-29 02:20
There is unfortunately a limit to how much data Chrome will allow an extension to write at once (saving the "library"). I'm not sure of the exact limit but somewhere north of 180-200+ decks seems this error starts occurring. I've found a way to chunk out the write, going to try and see if that resolves this issue, hopefully have a fix for this sometime later this week.

**Comment by david-torres** [comment] 2019-07-31 15:20
I tried to use a class I found that supposedly addresses this issue by chunking the data into smaller writes but still hit the quota. So next I tried writing a record for each deck instead of a giant blob, but THAT hits the max writes per minute quota. Need to do some research to figure out how people get around this...

**Comment by Cloggin** [comment] 2019-08-15 05:06
I know this issues already on your list, Torres, but I'm going to bump this thread anyway. (260+ decks trying to import to (any) of the supported sides.)

**Comment by david-torres** [comment] 2019-08-22 15:27
I have a pull request (https://github.com/funkymonkeymonk/library-access/pull/3/files) that _should_ fix this issue. However, since I can only simulate the problem I'd love it if someone that actually has this problem could check it out and see if this code fixes it.

**Comment by scrowner** [comment] 2019-08-23 23:35
David,

  It does the same thing for me. Do I need to do a re-install of the app?

Scot

**Comment by Cloggin** [comment] 2019-08-24 13:50
I'm able to hit the extension while on Master Vault, and it tells me it scooped up the decks, but when I return to a site to import what's been slurped up, no dice.

<img width="155" alt="Screen Shot 2019-08-24 at 8 47 21 AM" src="https://user-images.githubusercontent.com/599093/63638286-eba7cb80-c64b-11e9-8c13-ed4b865572ca.png">

<img width="149" alt="Screen Shot 2019-08-24 at 8 47 29 AM" src="https://user-images.githubusercontent.com/599093/63638288-efd3e900-c64b-11e9-8006-1de3f6665869.png">

(Update)

And after a removal/re-install/good-ol-fashion-windows-style-restart:

<img width="148" alt="Screen Shot 2019-08-24 at 8 53 46 AM" src="https://user-images.githubusercontent.com/599093/63638381-c4053300-c64c-11e9-9cc0-3fa71a53a70d.png">

<img width="143" alt="Screen Shot 2019-08-24 at 8 53 54 AM" src="https://user-images.githubusercontent.com/599093/63638384-c798ba00-c64c-11e9-9c4b-adf4eb9a5c47.png">

Still no dice.

**Comment by david-torres** [comment] 2019-08-24 17:35
Sorry, to be clear here, I have not published a new version, I'm talking specifically about the development version posted here. You'd have to be following the installation instructions in the README. Otherwise, just hang tight, a new version will be published soon.

**Comment by Cloggin** [comment] 2019-08-24 17:50
Hey, to be clear, I'm a moron and should've been paying attention, bwhahahaha. I'm excited, obviously, and jumped the gun. IGNORE ME (hastag venturebrothers)

**Comment by scrowner** [comment] 2019-08-25 15:48
0.4 let me load in 305 decks from the Vault into DOK! Thank you.

**Comment by david-torres** [comment] 2019-08-25 16:23
Awesome was just about to post that I published the new version last night. Glad to hear the issue is confirmed to be fixed.

**Closed as completed** 2019-08-26 13:47 UTC
